### ISSUE TITLE
C3 Probability & Statistics for Machine Learning & Data Science

### ISSUE THREAD

**Issue by pasamelaspapas** [Rabbia-Hassan/Mathematics-for-Machine-Learning-and-Data-Science-Specialization-by-DeepLearning.AI#2]
Hi there, are you gonna upload the C3 answers? if so, when?

**Comment by Rabbia-Hassan** [comment]
Hello, thank you for your interest. I have started working on C3. I will be uploading the first week's content on this saturday InshaAllah. I have taken up on it. Hopefully I will be uploading rest of th weeks soon too.

**Comment by pasamelaspapas** [comment]
thanks man, very helpful

**Comment by Rabbia-Hassan** [comment]
@pasamelaspapas  I have uploaded some of the content of week1, working on more :)

**Comment by Rabbia-Hassan** [comment]
feel free to re open
